services:
  nestjs01_tutorial: 
    build: .
    ports: 
      - "3000:3000"
    volumes:
      - ./src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3000
  # Running mysql in docker 
  mysql_db:
    image: mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootsdfsdferwerwe
      MYSQL_DATABASE: nestjs_01_tutorial
      MYSQL_USER: root12345
      MYSQL_PASSWORD: rootsdfsdferwerweroot12345
      MYSQL_TCP_PORT: 3307

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql_db 
      PMA_USER: root12345
      PMA_PASSWORD: rootsdfsdferwerweroot12345
      PMA_ARBITRARY: 1
      PMA_PORT: 3307
    depends_on:
      - mysql_db
    # volumes:
    # - ./docker/custom_mysql_config:/docker-entrypoint-initdb.d