services:
  api_gateway: 
    build: ./http-api-gateway
    ports: 
      - "3000:3000"
    volumes:
      - ./http-api-gateway/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3000
  users_microservice: 
    build: ./users-microservice
    volumes:
      - ./users-microservice/src:/usr/src/app/src
    command: npm run start:dev
  payments_microservice: 
    build: ./payments-microservice
    volumes:
      - ./payments-microservice/src:/usr/src/app/src
    command: npm run start:dev
  nats: 
    image: nats
    ports: 
      - 4222:4222
  # Running mysql in docker 
  mysql_db:
    image: mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nestjs_db
      MYSQL_USER: root12345
      MYSQL_PASSWORD: root12345
      MYSQL_TCP_PORT: 3307

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql_db 
      PMA_USER: root12345
      PMA_PASSWORD: root12345
      PMA_ARBITRARY: 1
      PMA_PORT: 3307
    depends_on:
      - mysql_db